//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardAb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abiturient
    {
        public int ID { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Телефон { get; set; }
        public int Социальный_статус { get; set; }
        public int Id_Паспорта { get; set; }
        public int Id_Заявления { get; set; }
        public int Id_Аттестата { get; set; }
    
        public virtual Attestat Attestat { get; set; }
        public virtual Declaration Declaration { get; set; }
        public virtual Pasport Pasport { get; set; }
        public virtual Status Status { get; set; }
    }
}
