//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardAb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attestat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attestat()
        {
            this.Abiturient = new HashSet<Abiturient>();
        }
    
        public int id { get; set; }
        public int Серия_аттестата { get; set; }
        public string Номер_аттестата { get; set; }
        public System.DateTime Дата_выдачи { get; set; }
        public int Кем_выдан { get; set; }
        public double Средний_балл { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abiturient> Abiturient { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
