//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardAb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declaration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Declaration()
        {
            this.Abiturient = new HashSet<Abiturient>();
        }
    
        public int id { get; set; }
        public int Оригинал_атестата { get; set; }
        public int Оригинал_паспорта { get; set; }
        public int Фото { get; set; }
        public int Медицинская_справка { get; set; }
        public int Общежитие { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abiturient> Abiturient { get; set; }
    }
}
